name: sendify
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  dartz: ^0.9.2
  flutter_bloc: ^7.0.0
  cupertino_icons: ^1.0.2
  get_it: ^6.0.0
  expandable: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
